NumPy stands for Numerical Python.

NumPy is a python library used for working with arrays.

Why Use NumPy ?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.


Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

In [1]:
import numpy as num
l=[1,2,3,4]
print(num.array(l))


[1 2 3 4]


In [2]:
print(type(l))

<class 'list'>


In [3]:
l=[1,2,3,4]
x1=num.array(l)
print(type(x1))

<class 'numpy.ndarray'>


In [4]:
print('dimension of numpy array is',x1.ndim)


dimension of numpy array is 1


In [5]:
print('shape of numpy array is',x1.shape)

shape of numpy array is (4,)


In [6]:
l=[[1],[2],[3],[4]]
x1=num.array(l)
print(type(x1))
print('dimension of numpy array is',x1.ndim)
print('shape of numpy array is',x1.shape)

<class 'numpy.ndarray'>
dimension of numpy array is 2
shape of numpy array is (4, 1)


In [7]:
l=[[1,0],[2,8],[3,2],[4,2]]
x1=num.array(l)
print(x1)
print(type(x1))
print('dimension of numpy array is',x1.ndim)
print('shape of numpy array is',x1.shape)

[[1 0]
 [2 8]
 [3 2]
 [4 2]]
<class 'numpy.ndarray'>
dimension of numpy array is 2
shape of numpy array is (4, 2)


In [8]:
l=[[[1,2,3],[1,2,3]],[[1,2,3],[3,4,5]],[[1,2,3],[1,2,3]]]
x1=num.array(l)
print(x1)
print(type(x1))
print('dimension of numpy array is',x1.ndim)
print('shape of numpy array is',x1.shape)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [3 4 5]]

 [[1 2 3]
  [1 2 3]]]
<class 'numpy.ndarray'>
dimension of numpy array is 3
shape of numpy array is (3, 2, 3)


In [9]:
#operations on numpy array

In [10]:
# create two 3 by 3 matrices

In [11]:
a=[[23,45,12],[11,3,23],[54,34,22]]
b=[[44,5,3],[33,22,1],[43,5,12]]
a=num.array(a)
b=num.array(b)
print(a)
print(b)

[[23 45 12]
 [11  3 23]
 [54 34 22]]
[[44  5  3]
 [33 22  1]
 [43  5 12]]


In [12]:
#additon operation
print(a+b)


[[67 50 15]
 [44 25 24]
 [97 39 34]]


In [13]:
#subtraction operation
print(a-b)

[[-21  40   9]
 [-22 -19  22]
 [ 11  29  10]]


In [14]:
#multipication operation
print(a*b)

[[1012  225   36]
 [ 363   66   23]
 [2322  170  264]]


In [15]:
#divison operation
print(a/b)

[[ 0.52272727  9.          4.        ]
 [ 0.33333333  0.13636364 23.        ]
 [ 1.25581395  6.8         1.83333333]]


In [16]:
#xor operation
print(a^b)

[[59 40 15]
 [42 21 22]
 [29 39 26]]


In [17]:
#martix mutliplication of a and b is done if "now of cloumns of a =now of rows of b"
print(a@b)

[[3013 1165  258]
 [1572  236  312]
 [4444 1128  460]]


In [18]:
#transpose of a 
print(a)
print(a.T)

[[23 45 12]
 [11  3 23]
 [54 34 22]]
[[23 11 54]
 [45  3 34]
 [12 23 22]]


In [19]:
x=num.array([[1,2,3]])
print(x,x.shape,"\n")
x_trans=x.T
print(x_trans,x_trans.shape)

[[1 2 3]] (1, 3) 

[[1]
 [2]
 [3]] (3, 1)


In [20]:
#ravel() fun flats the matrix 
print(a.ravel())

[23 45 12 11  3 23 54 34 22]


In [21]:
# vertical stack 'vstack()' concating two arrays
#note : concating two arrays possible if and only if two arrays having same no.of columns.. 
print(x,x.shape)
print()
print(a,a.shape,"\n")
print(num.vstack((a,x)))

[[1 2 3]] (1, 3)

[[23 45 12]
 [11  3 23]
 [54 34 22]] (3, 3) 

[[23 45 12]
 [11  3 23]
 [54 34 22]
 [ 1  2  3]]


In [22]:
print((a,x))

(array([[23, 45, 12],
       [11,  3, 23],
       [54, 34, 22]]), array([[1, 2, 3]]))


In [23]:
#horizontal stacing is done only if two arrays having same no of rows
z=num.hstack((a,b))
print(z,z.shape)

[[23 45 12 44  5  3]
 [11  3 23 33 22  1]
 [54 34 22 43  5 12]] (3, 6)


In [24]:
#resize opeartor
print(a,"\n")
re_a=num.resize(a,(5,2))
print(re_a)

[[23 45 12]
 [11  3 23]
 [54 34 22]] 

[[23 45]
 [12 11]
 [ 3 23]
 [54 34]
 [22 23]]


In [25]:
re_a=num.resize(a,(6,2))
print(re_a)

[[23 45]
 [12 11]
 [ 3 23]
 [54 34]
 [22 23]
 [45 12]]


In [26]:
                                                 #algebric operations

In [27]:
# 1 determinate of matrix

In [28]:
print(a)
print()
print(num.linalg.det(a))

[[23 45 12]
 [11  3 23]
 [54 34 22]]

31075.999999999993


In [29]:
#find in the inverse of matric A


In [30]:
print(a)
print()
inv=num.linalg.inv(a)
print(inv)
print()
print(inv.round(0))

[[23 45 12]
 [11  3 23]
 [54 34 22]]

[[-0.02304029 -0.01872828  0.03214699]
 [ 0.03217917 -0.00456944 -0.01277513]
 [ 0.00682198  0.05303128 -0.01370833]]

[[-0. -0.  0.]
 [ 0. -0. -0.]
 [ 0.  0. -0.]]


In [31]:
#log(a)
print(num.log(a))


[[3.13549422 3.80666249 2.48490665]
 [2.39789527 1.09861229 3.13549422]
 [3.98898405 3.52636052 3.09104245]]


In [32]:
#sin(a),tan(a),cos(a) ..... etc...
print(num.sin(a))

[[-0.8462204   0.85090352 -0.53657292]
 [-0.99999021  0.14112001 -0.8462204 ]
 [-0.55878905  0.52908269 -0.00885131]]


In [33]:
#exponintial
print(num.exp(a))

[[9.74480345e+09 3.49342711e+19 1.62754791e+05]
 [5.98741417e+04 2.00855369e+01 9.74480345e+09]
 [2.83075330e+23 5.83461743e+14 3.58491285e+09]]


In [34]:
#sum,max,min operators...

In [35]:
#sum...
print(a)
print()
print(a.sum())
print()
print(a.sum(axis=0))
print()
print(a.sum(axis=1))

[[23 45 12]
 [11  3 23]
 [54 34 22]]

227

[88 82 57]

[ 80  37 110]


In [36]:
#max...
print(a)
print()
print(a.max())
print()
print(a.max(axis=0))
print()
print(a.max(axis=1))

[[23 45 12]
 [11  3 23]
 [54 34 22]]

54

[54 45 23]

[45 23 54]


In [37]:
#min...
print(a)
print()
print(a.min())
print()
print(a.min(axis=0))
print()
print(a.min(axis=1))

[[23 45 12]
 [11  3 23]
 [54 34 22]]

3

[11  3 12]

[12  3 22]


In [38]:
import numpy as num
a=[[23,45,12],[11,3,23],[54,34,22]]
b=[[44,5,3],[33,22,1],[43,5,12]]
a=num.array(a)
b=num.array(b)
print(a)
print(b)

[[23 45 12]
 [11  3 23]
 [54 34 22]]
[[44  5  3]
 [33 22  1]
 [43  5 12]]


In [39]:
print(a+10)#10 is added to each and every element

[[33 55 22]
 [21 13 33]
 [64 44 32]]


In [40]:
x=num.array([[1],[2],[3]])#column vector[3,1]
y=num.array([[1,2,3]])#row vector[1,3]

In [41]:
print(a,"\n")#[3,3]
print(a+x)

[[23 45 12]
 [11  3 23]
 [54 34 22]] 

[[24 46 13]
 [13  5 25]
 [57 37 25]]


In [42]:
print(a+y)

[[24 47 15]
 [12  5 26]
 [55 36 25]]


In [43]:
print(x+y)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [44]:
#range: we can create num py array by using range
A=num.arange(10)#upto 9 values
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [45]:
print(num.resize(A,(3,3)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [46]:
#creating zeros matrix
A=num.zeros((2,4))
print(A)
print()
B=num.ones((2,4))
print(B)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [47]:
#we can create an identity matrix by using eye()
I=num.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
#random valued matrix by random.random()
A=num.random.random((2,2))
print(A)

[[0.57707727 0.28771918]
 [0.98140637 0.80219191]]


In [49]:
x=num.random.randint(1,21,size=(5,4))
x

array([[ 8, 12, 15, 13],
       [ 2, 16, 13, 20],
       [17,  5,  6, 13],
       [10, 20, 10, 13],
       [ 2,  5,  3, 13]])

In [58]:
x=num.random.randint(1,21,size=(5,4))
x

array([[ 5, 14, 13, 17],
       [18, 20,  2, 17],
       [10, 13,  2,  1],
       [14, 15, 13,  6],
       [11, 19,  3, 16]])

In [51]:
# indexins and slicing on num.arrays=  x[rows:cols]
x[1:]

array([[ 4, 16, 10,  5],
       [20,  7, 18,  8],
       [ 2,  1, 14,  6],
       [17,  7, 20, 16]])

In [52]:
x[:2]

array([[16, 14, 19, 13],
       [ 4, 16, 10,  5]])

In [53]:
x[:]

array([[16, 14, 19, 13],
       [ 4, 16, 10,  5],
       [20,  7, 18,  8],
       [ 2,  1, 14,  6],
       [17,  7, 20, 16]])

In [54]:
x[2:3]

array([[20,  7, 18,  8]])

In [55]:
#retriving for perticular element from array we use x[row_position,col_postion]
x[1,3]

5

In [64]:
x[1,3]=num.nan

In [65]:
x=num.random.randint(1,21,size=(5,4)).astype(num.float)
x

array([[ 3., 10., 15., 14.],
       [12., 14., 11., 17.],
       [ 7., 18.,  6., 20.],
       [12., 16.,  8., 14.],
       [14., 18., 20., 14.]])

In [66]:
#assinging 'NaN' vlaues at partucular position
x[2,3]=num.nan
x

array([[ 3., 10., 15., 14.],
       [12., 14., 11., 17.],
       [ 7., 18.,  6., nan],
       [12., 16.,  8., 14.],
       [14., 18., 20., 14.]])

In [67]:
x[3,:]=num.nan
x

array([[ 3., 10., 15., 14.],
       [12., 14., 11., 17.],
       [ 7., 18.,  6., nan],
       [nan, nan, nan, nan],
       [14., 18., 20., 14.]])

In [68]:
#converting above array into dataframe
import pandas as pd
df=pd.DataFrame(data=x,columns=['A','B','C','D'])
df.head(5)

A     B     C     D
0   3.0  10.0  15.0  14.0
1  12.0  14.0  11.0  17.0
2   7.0  18.0   6.0   NaN
3   NaN   NaN   NaN   NaN
4  14.0  18.0  20.0  14.0

In [69]:
#eliminating rows with nan values use axis=0 ,similarly for cols use axis=1
df.dropna(axis=0)

A     B     C     D
0   3.0  10.0  15.0  14.0
1  12.0  14.0  11.0  17.0
4  14.0  18.0  20.0  14.0

In [70]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [71]:
df[['A']].fillna(0)

A
0   3.0
1  12.0
2   7.0
3   0.0
4  14.0

In [72]:
df.fillna(0)

A     B     C     D
0   3.0  10.0  15.0  14.0
1  12.0  14.0  11.0  17.0
2   7.0  18.0   6.0   0.0
3   0.0   0.0   0.0   0.0
4  14.0  18.0  20.0  14.0

In [83]:
#eliminating rows which contains all nan values/similarly for cols
df.dropna(axis=0,how='all')

A     B     C     D
0  17.0  10.0   8.0   7.0
1  18.0   7.0  20.0  20.0
2   2.0   1.0   2.0   NaN
4   3.0  10.0  16.0  14.0

In [74]:
import numpy as np
import pandas as pd
x=np.random.randint(1,21,size=(5,4)).astype(np.float)
df=pd.DataFrame(data=x,columns=['A','B','C','D'])
df.head(5)

A     B     C     D
0  17.0  10.0   8.0   7.0
1  18.0   7.0  20.0  20.0
2   2.0   1.0   2.0  17.0
3  12.0  14.0  19.0  11.0
4   3.0  10.0  16.0  14.0

In [75]:
x[2,3]=np.nan

In [76]:
x[3,:]=np.nan

In [77]:
df

A     B     C     D
0  17.0  10.0   8.0   7.0
1  18.0   7.0  20.0  20.0
2   2.0   1.0   2.0   NaN
3   NaN   NaN   NaN   NaN
4   3.0  10.0  16.0  14.0

In [84]:
#eliminating rows with nan values in cols['c']
df.dropna(axis=0,subset=['C'])
df

A     B     C     D
0  17.0  10.0   8.0   7.0
1  18.0   7.0  20.0  20.0
2   2.0   1.0   2.0   NaN
3   NaN   NaN   NaN   NaN
4   3.0  10.0  16.0  14.0

In [79]:
#eliminating rows with less than 'n' 
ans=df.dropna(axis=0,thresh=4)
ans

A     B     C     D
0  17.0  10.0   8.0   7.0
1  18.0   7.0  20.0  20.0
4   3.0  10.0  16.0  14.0

In [80]:
df

A     B     C     D
0  17.0  10.0   8.0   7.0
1  18.0   7.0  20.0  20.0
2   2.0   1.0   2.0   NaN
3   NaN   NaN   NaN   NaN
4   3.0  10.0  16.0  14.0